import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — kodean" },
      {
        name: "description",
        content: "How the kodean browser extension handles your data.",
      },
    ],
  }),
  component: PrivacyPolicy,
});

const LAST_UPDATED = "July 8, 2026";

function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background text-foreground font-sans antialiased">
      <header className="sticky top-0 z-50 border-b border-border/60 bg-background/70 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-6">
          <Link to="/" className="text-[15px] font-semibold tracking-tight">
            <i>
              <b>kodean</b>
            </i>
          </Link>
          <Link
            to="/"
            className="text-sm text-muted-foreground transition-colors hover:text-foreground"
          >
            Back to home
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="text-3xl font-semibold tracking-tight">Privacy Policy</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>

        <div className="mt-10 space-y-10 text-[15px] leading-relaxed text-muted-foreground">
          <Section title="What kodean does">
            <p>
              kodean is a browser extension that explains code you highlight on supported
              developer websites. This policy describes what data the extension handles and
              where it goes.
            </p>
          </Section>

          <Section title="Data we process">
            <p>When you click "Explain" on a highlighted code snippet, the extension sends:</p>
            <ul className="mt-3 list-disc space-y-1.5 pl-6">
              <li>the code you selected,</li>
              <li>the title of the page you are on, and</li>
              <li>the website's hostname (for example, github.com).</li>
            </ul>
            <p className="mt-3">
              This is sent to our API (hosted on Cloudflare Workers), which forwards it to an
              AI model provider (Groq) to generate the explanation. Nothing is sent anywhere
              until you explicitly click Explain.
            </p>
          </Section>

          <Section title="What we do NOT collect">
            <ul className="list-disc space-y-1.5 pl-6">
              <li>No account, name, email, or other personal information.</li>
              <li>No browsing history — the extension only reacts to text you highlight on supported sites.</li>
              <li>No analytics, tracking pixels, or third-party advertising.</li>
              <li>We do not store your code selections on our servers after the explanation is generated.</li>
            </ul>
          </Section>

          <Section title="Data stored on your device">
            <p>
              Learning data such as saved snippets and practice progress is stored locally in
              your browser using the extension's storage. It stays on your device and is
              removed when you uninstall the extension.
            </p>
          </Section>

          <Section title="Third parties">
            <p>
              Explanations are generated by Groq, whose processing of the submitted snippet is
              governed by their own privacy policy. We share only what is listed above — never
              more.
            </p>
          </Section>

          <Section title="Changes to this policy">
            <p>
              If we change how kodean handles data, we will update this page and the "Last
              updated" date above.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions? Email{" "}
              <a
                href="mailto:siddheshkasat.sk@gmail.com"
                className="text-foreground underline underline-offset-4"
              >
                siddheshkasat.sk@gmail.com
              </a>
              .
            </p>
          </Section>
        </div>
      </main>

      <footer className="border-t border-border/60 py-10">
        <p className="text-center text-xs text-muted-foreground/70">
          © {new Date().getFullYear()} <b><i>kodean</i></b>. All rights reserved.
        </p>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      <div className="mt-3">{children}</div>
    </section>
  );
}
